version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - "./.env"
    networks:
      - back
  
  wordpress:
    depends_on:
        - db
    image: wordpress:4.9.4 
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
    env_file:
      - "./.env"
    ports:
      - "4000:80"
    networks:
      - back
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8081:80"
    env_file:
      - "./.env"
    networks:
      - back

  my-wpcli:
    depends_on:
        - wordpress
    image: tatemz/wp-cli
    volumes:
      - ./wordpress:/var/www/html
    links:
      - db:mysql
    entrypoint: wp  
    command: "--info"
networks:
  back:
volumes:
  db_data:
  